module.exports = (app, container) => {
  const { serverSettings } = container.resolve('config')
  const { userController } = container.resolve('controller')
  const { verifyAccessToken } = container.resolve('middleware')
  const { basePath } = serverSettings
  app.post(`${basePath}/login`, userController.loginOrRegister)
  app.post(`${basePath}/refreshToken`, userController.refreshToken)
  app.post(`${basePath}/enterGuest`, userController.enterGuest)
  app.get(`${basePath}/ping`, userController.ping)
  app.put(`${basePath}/cms/user/:uid`, verifyAccessToken, userController.updateUserInfo)
  app.put(`${basePath}/cms/user/block/:uid`, verifyAccessToken, userController.blockUser)
  app.get(`${basePath}/cms/user/session/:uid`, verifyAccessToken, userController.getSessions)
  app.get(`${basePath}/cms/user/history/:uid`, verifyAccessToken, userController.getHistoryByUid)
  app.delete(`${basePath}/cms/user/session/:uid`, verifyAccessToken, userController.deleteSessionByUid)
  app.delete(`${basePath}/cms/user/session/:uid/:id`, verifyAccessToken, userController.deleteSessionById)
  app.get(`${basePath}/cms/user`, verifyAccessToken, userController.getUsers)
  app.get(`${basePath}/verifyToken`, userController.verifyToken)
  app.get(`${basePath}/details`, userController.getUserDetail)
  app.get(`${basePath}/detailCache`, userController.getUserFromCache)
  app.get(`${basePath}/users`, userController.getListUserByIds)
  app.post(`${basePath}/logout`, userController.logout)
  app.post(`${basePath}/saveLanguage`, userController.saveLanguage)
  app.get(`${basePath}/language`, userController.getUserDetailCache)
  app.get(`${basePath}/authorization`, userController.authorization)
  app.post(`${basePath}/phones`, userController.loginOrRegisterByPhone)
  app.patch(`${basePath}/information`, userController.updateUserInforById)
  app.patch(`${basePath}/coverpage`, userController.updateCoverPage)
  app.patch(`${basePath}/fcmtoken`, userController.refreshFcmToken)
  app.patch(`${basePath}/changePassword`, userController.changePassword)
  app.post(`${basePath}/signup`, userController.signUpUser)
  app.post(`${basePath}/loginEmail`, userController.loginUser)
}
